[env]
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    ArduinoJson

[env:esp8266]
platform = espressif8266
board = nodemcuv2
build_flags = -DESP8266

[env:esp32]
platform = espressif32
board = esp32doit-devkit-v1
build_flags = -DESP32
